### ISSUE TITLE
support for multiple sets of custom holidays

### ISSUE THREAD

**Issue by mapshen** [allangood/holiday_exporter#7]
The use case is to accommodate the needs of different organizations, which follow different holiday schedules. 

I would imagine the configs go like this:
```
custom_holidays:
  - name: test
    region: us
    organization: A
    schedule:
    - date: "2019-12-17"
      description: "Some day this year only"
```

Other than the mandatory `schedule` field, the others are free-form key-value pairs (containing at least 1 pair), which translate to the labels of the `is_holiday` metric. Perhaps we can make `name` mandatory as well.

@allangood Do you think this is can be something we add?
